const LOGON = 'LOGON'
const SIGNUP = 'SIGNUP'
const LOGOUT = 'LOGOUT'
const UPDATEUSER = 'UPDATEUSER'
const REMOVEUSER = 'REMOVEUSER'
const ACTIVEUSER = 'ACTIVEUSER'
const SEARCH = 'SEARCH'
const ACTION = { ALL: 'ALL', ACTIVE: 'ACTIVE', INACTIVE: 'INACTIVE' }
const SORT = { AZ: 'A-Z', ZA: 'Z-A' }

const ERROR = 'ERROR'
const SUCCESS = 'SUCCESS'

export {
    LOGON,
    SIGNUP,
    LOGOUT,
    UPDATEUSER,
    REMOVEUSER,
    ACTIVEUSER,
    SEARCH,
    ACTION,
    SORT,
    ERROR,
    SUCCESS,
}